FROM postgres:16

ENV POSTGRES_PORT 5432
ENV POSTGRES_USER testuser
ENV POSTGRES_PASSWORD test
ENV POSTGRES_DB mobile_lines_db

COPY ./db/scripts/createTables.sql /docker-entrypoint-initdb.d
COPY ./db/scripts/insertConfigData.sql /docker-entrypoint-initdb.d

RUN chmod +x /docker-entrypoint-initdb.d/createTables.sql
RUN chmod +x /docker-entrypoint-initdb.d/insertConfigData.sql

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["postgres"]