version: '3.2'
services:

  # Uncomment this piece of code to use the wiremock container
    wiremock:
      image: wiremock/wiremock:latest
      working_dir: /home/wiremock
      container_name: wiremock
      volumes:
        - ../src/test/resources/exploratory/mappings:/home/wiremock/mappings
        - ../src/test/resources/exploratory/files:/home/wiremock/__files
      ports:
        - "8089:8089"
      entrypoint: ["/docker-entrypoint.sh", "--local-response-templating", "--disable-gzip", "--verbose"]
      command:
        --port 8089
        --max-request-journal-entries 1000
        --verbose
        --global-response-templating
