version: '3.2'
services:

  postgres:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile-db
    restart: always
    volumes:
      - ./db:/tmp/db

  wiremock:
    image: wiremock/wiremock:2.32.0
    working_dir: /home/wiremock
    container_name: wiremock
    volumes:
      - ../src/test/resources/wiremock/mappings:/home/wiremock/mappings
      - ../src/test/resources/wiremock/__files:/home/wiremock/__files
    ports:
      - "28601:28601"
    command: --port 28601 --max-request-journal-entries 1000 --verbose

  app:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    environment:
      - APPHOST=app
      - DBSERVER=postgres
      - cargos_api_base-url=http://wiremock:28601
    depends_on:
      - postgres
      - wiremock

  karate:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile-karate
    environment:
      - ARTIFACTORY_REPO_USER=${ARTIFACTORY_REPO_USER}
      - ARTIFACTORY_REPO_PWD=${ARTIFACTORY_REPO_PWD}
      - APPHOST=app
      - DBSERVER=postgres
    depends_on:
      - postgres
      - wiremock
      - app
